learning_logs/urls.py
"""Defining URL patterns for learning logs"""

#path function is needed when mapping URLs to views hence we have to import it
from django.urls import path
from . import views #dot refers to current directory so importing views from current directory

app_name = 'learning_logs'

#list of individual pages that can be requested from the learning_logs app
"""
path function takes 3 arguments
    1) String tht helps Django route the current request properly
    2) Specifies which function to call in views.py
    3) Provides name index for this URL pattern so we can refer to it more easily in other files throughout the project
"""
urlpatterns = [
    #Home page
    path('', views.index, name='index'),
    #Path to show all topics.
    path('topics/', views.topics, name='topics'),
    #Detail page for a single topic.
    path('topics/<int:topic_id>/', views.topic, name='topic'),
]

ll_project/urls.py
#Tells Django which pages to build in response to browser requests

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('learning_logs.urls')),
]

learning_logs/models.py
from django.db import models

# Create your models here.
# We will define the data we want to manage in our app
# We(user) will create multiple topic in learning log and and the entry they will make will be tied to a topic
# We will also store timestamp of each entry



class Topic(models.Model):
    """A topic the user is learning about."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Returning string representation of Model"""
        return self.text

    """
    If a model has a __str__() method, 
    Django calls that method whenever it needs to generate output referring to an instance of that model
    """

class Entry(models.Model):
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'
    
    def __str__(self):
        "Returning simple string representing the entry"
        if len(self.text) > 50:
            return f"{self.text[:50]}..."
        else:
            return f"{self.text}"

learning_logs/views.py
from django.shortcuts import render
from .models import Topic

# Create your views here.
#it takes info from requests, prepares the data needed to generate a page, and then sends the data back to the browser

def index(request):
    """The home page for Learning Log."""
    return render(request, 'learning_logs/index.html')

def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)

def topic(request, topic_id):
    "Showing single topic and all its entries"
    topic = Topic.objects.get(id=topic_id) #queries
    entries = topic.entry_set.order_by('-date_added') #queries
    context = {'topic': topic, 'entries':entries}
    return render(request, 'learning_logs/topic.html', context)

learning_logs/templates/learning_logs/base.html
<!-- This file will contain elements common to all the pages -->

<p>
    <a href="{% url 'learning_logs:index' %}">Learning Log</a> -
    <a href="{% url 'learning_logs:topics' %}">Topics</a>
</p>
{% block content %}{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends 'learning_logs/base.html' %}

{% block content %}
<p>Learning Log helps you keep track of your learning, for any topic you're interested in.</p>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}

{% block content %}

<p>Topic: {{ topic.text }}</p>

<p>Entries:</p>
<ul>
    {% for entry in entries %}
        <li>
            <p>{{ entry.date_added|date:'M d, Y H:i' }}</p>
            <p>{{ entry.text|linebreaks }}</p>
        </li>
    {% empty %}
        <li>There are no entries for this topic yet.</li>
    {% endfor %}
</ul>    

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends 'learning_logs/base.html' %}

{% block content %}

    <p>Topics</p>
    <ul>
        {% for topic in topics %}
            <li>
                <a href="{% url 'learning_logs:topic' topic.id %}">
                    {{ topic.text }}</a>
            </li>
        {% empty %}
            <li>No topics have been added yet.</li>
        {% endfor %}    
    </ul>

{% endblock content %}